### ISSUE TITLE
some bug to connecting links

### ISSUE THREAD

**Issue by Ulugbek-Mominjonov** [OzodaKhamdamova/scoot#14]
![image](https://user-images.githubusercontent.com/79502241/117541806-05ab5c80-b02f-11eb-85be-4e0600313e3b.png)
Muhammadjavohir akaning tavsiyasi bo'yicha o'zimizning asosiy stillar normaliza.css va boshqa css fayllaridan keyin ulanishi kerak
Agar bunday qilinmasa normaliza css siz yozgan stillar to'g'ri ishlashiga halaqit beradi

**Comment by OzodaKhamdamova** [comment]
ok)
