### ISSUE TITLE
some advice for footer

### ISSUE THREAD

**Issue by Ulugbek-Mominjonov** [OzodaKhamdamova/scoot#16]
![image](https://user-images.githubusercontent.com/79502241/117542368-c8949980-b031-11eb-9d91-de575bf2017f.png)
social-section bu bo'lim footer ichida bo'lishi kerakov chunki u sitening barcha sahifasida birxil(footer sifadida) header kabi

**Comment by OzodaKhamdamova** [comment]
ok) corrected
