### ISSUE TITLE
link hover bo'lsa width kattalashyapti

### ISSUE THREAD

**Issue by ShokhrukhTurgunov** [OzodaKhamdamova/scoot#3]
![Screenshot_3](https://user-images.githubusercontent.com/77617034/117435401-4334ba80-af47-11eb-8cdb-659a01d9506f.png)
oddiy holatiga ham hoverdagi borderni berib qo'ysangiz bir xil bo'ladi

**Comment by OzodaKhamdamova** [comment]
comitted
